local M = {}

local palette = {
  fg = "#c0caf5",
  black = "#414868",
  red = "#e87088",
  crimson = "#DC143C",
  green = "#9ece6a",
  yellow = "#dec76e",
  orange = "#ff9e64",
  blue = "#7aa2f7",
  magenta = "#bb9af7",
  cyan = "#7dcfff",
  white = "#d4daf2",
}

local function apply()
  local set = vim.api.nvim_set_hl

  local groups = {
    Normal = palette.fg,
    NormalNC = palette.fg,
    NormalFloat = palette.fg,
    FloatBorder = palette.blue,
    FloatTitle = palette.blue,
    MsgSeparator = palette.crimson,
    CursorLineNr = palette.white,
    LineNr = palette.black,
    NonText = palette.black,
    Whitespace = palette.black,
    Title = palette.blue,
    Comment = palette.black,
    Constant = palette.yellow,
    String = palette.green,
    Character = palette.cyan,
    Number = palette.yellow,
    Boolean = palette.orange,
    Float = palette.yellow,
    Identifier = palette.red,
    Function = palette.blue,
    Statement = palette.magenta,
    Conditional = palette.magenta,
    Repeat = palette.magenta,
    Label = palette.red,
    Operator = palette.cyan,
    Keyword = palette.magenta,
    Exception = palette.magenta,
    PreProc = palette.cyan,
    Include = palette.magenta,
    Define = palette.cyan,
    Macro = palette.cyan,
    Type = palette.yellow,
    StorageClass = palette.magenta,
    Structure = palette.yellow,
    Typedef = palette.yellow,
    Special = palette.yellow,
    SpecialChar = palette.cyan,
    Tag = palette.red,
    Delimiter = palette.white,
    Debug = palette.yellow,
    Underlined = palette.magenta,
    DiagnosticError = palette.red,
    DiagnosticWarn = palette.yellow,
    DiagnosticInfo = palette.blue,
    DiagnosticHint = palette.cyan,
    htmlTag = palette.white,
    htmlEndTag = palette.white,
    htmlTagN = palette.red,
    htmlTagName = palette.red,
    htmlSpecialTagName = palette.red,
    htmlArg = palette.blue,
    tsxTagName = palette.yellow,
    tsxIdentifierName = palette.yellow,
    tsxAttrib = palette.blue,
    typescriptExport = palette.magenta,
    typescriptImport = palette.magenta,
    typescriptKeyword = palette.magenta,
    typescriptStatement = palette.magenta,
    typescriptReserved = palette.magenta,
    typescriptConst = palette.magenta,
    typescriptStorageClass = palette.magenta,
    typescriptVariableDeclaration = palette.yellow,
  }

  for group, color in pairs(groups) do
    set(0, group, { fg = color })
  end

  local treesitter_groups = {
    ["@comment"] = palette.black,
    ["@string"] = palette.green,
    ["@character"] = palette.cyan,
    ["@number"] = palette.yellow,
    ["@boolean"] = palette.orange,
    ["@float"] = palette.yellow,
    ["@constant"] = palette.yellow,
    ["@constant.builtin"] = palette.yellow,
    ["@variable"] = palette.red,
    ["@variable.builtin"] = palette.yellow,
    ["@function"] = palette.blue,
    ["@function.builtin"] = palette.cyan,
    ["@function.macro"] = palette.cyan,
    ["@keyword"] = palette.magenta,
    ["@keyword.function"] = palette.magenta,
    ["@keyword.operator"] = palette.magenta,
    ["@keyword.export"] = palette.magenta,
    ["@keyword.import"] = palette.magenta,
    ["@keyword.storage"] = palette.magenta,
    ["@keyword.const"] = palette.magenta,
    ["@keyword.declaration"] = palette.magenta,
    ["@conditional"] = palette.magenta,
    ["@repeat"] = palette.magenta,
    ["@operator"] = palette.cyan,
    ["@type"] = palette.yellow,
    ["@type.builtin"] = palette.magenta,
    ["@type.tsx"] = palette.yellow,
    ["@type.definition"] = palette.yellow,
    ["@storageclass"] = palette.magenta,
    ["@namespace"] = palette.yellow,
    ["@parameter"] = palette.red,
    ["@property"] = palette.cyan,
    ["@field"] = palette.red,
    ["@tag"] = palette.red,
    ["@tag.attribute"] = palette.blue,
    ["@tag.builtin"] = palette.red,
    ["@tag.builtin.html"] = palette.red,
    ["@tag.html"] = palette.red,
    ["@tag.tsx"] = palette.yellow,
    ["@tag.delimiter"] = palette.white,
    ["@punctuation"] = palette.white,
    ["@punctuation.delimiter"] = palette.white,
    ["@punctuation.bracket"] = palette.white,
    ["@punctuation.special"] = palette.cyan,
    ["@punctuation.special.html"] = palette.white,
    ["@punctuation.bracket.html"] = palette.white,
    ["@punctuation.delimiter.html"] = palette.white,
    ["@punctuation.special.tsx"] = palette.white,
    ["@punctuation.bracket.tsx"] = palette.white,
    ["@punctuation.delimiter.tsx"] = palette.white,
    ["@constructor.tsx"] = palette.yellow,
    ["@attribute"] = palette.blue,
    ["@variable.constant"] = palette.yellow,
    ["@text.literal"] = palette.green,
    ["@text.uri"] = palette.green,
    ["@lsp.typemod.variable.readonly"] = palette.yellow,
    ["@lsp.typemod.variable.readonly.typescript"] = palette.yellow,
    ["@lsp.typemod.variable.readonly.tsx"] = palette.yellow,
    ["@lsp.type.keyword"] = palette.magenta,
    ["@lsp.typemod.keyword.declaration"] = palette.magenta,
    ["@lsp.typemod.keyword.readonly"] = palette.magenta,
  }

  for group, color in pairs(treesitter_groups) do
    set(0, group, { fg = color })
  end
end

function M.setup()
  apply()

  vim.api.nvim_create_autocmd("ColorScheme", {
    group = vim.api.nvim_create_augroup("TokyoGoghForeground", { clear = true }),
    callback = apply,
  })
end

return M
